version: "3"

services:
  react-app:
    container_name: react-tutorial
    image: node:16.17.0-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/react-app
    working_dir: /home/node/react-app
    user: node
    command: sh -c "npm install && npm start"
    tty: true
